services:
  web:
    container_name: fenix_frontend 
    build: 
      context: ./web
    ports:
      - "3000:3000"
      #- "3000:80" Production
    volumes:
      - ./web:/web
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file watching works on all OS and Docker setups

  backend:
    container_name: fenix_backend 
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file watching works on all OS and Docker setups
    #volumes:
    #  - ./backend:/app
